### ISSUE TITLE
How to use bundletool with cli

### ISSUE THREAD

**Issue by krestia** [google/bundletool#13]
Hi, how to use this bundletool and build an android app bundle from cordova cli?

**Comment by DilerxD** [comment]
Hi, i thing is the same for linux, check the steps here :smile: 
https://developer.android.com/guide/app-bundle/test

**Comment by DilerxD** [comment]
@krestia first i thing you need to read this documentation
**https://developer.android.com/guide/app-bundle/**

and the get started step for the creation of android app bundle apps is this:

![image](https://user-images.githubusercontent.com/10903169/40695456-e90cf720-6386-11e8-9b8d-ba869fc50cd6.png)

This steps works on linux because i use Ubuntu 18.04

**Comment by keyboardsurfer** [comment]
The implementation of such a command is responsibility of the build system provider.
In this case Cordova. Please refer to their issue reporting process and raise a feature request there.
