### ISSUE TITLE
Build a universal APK without zipping it into an APK set.

### ISSUE THREAD

**Issue by JonathanDotCel** [google/bundletool#148]
**Is your feature request related to a problem? Please describe.**

When sending APK files to testers before final releases, they must convert the .AAB to an APK set... which then has to be extracted, adding an extra step + time.

Would be nice to skip the APK set (and unzipping it) and just get the APKs or single Universal APK.

**Describe the solution you'd like**

A command line arg to skip the APK set and drop a regular unzipped universal APK to the directory instead.
-fewer redundant steps
-less error prone
-massive time saving

**Describe alternatives you've considered**
Scripting it, but it still takes longer and needs a unique filename.

**Additional context**
I think we're good.

Cheers!

**Comment by ymakhno** [comment]
As universal APK is just one of modes which is supported by `build-apks` command and there are other modes which produce multiple APKs we would like to keep bundletool behaviour consistent and not change output interface depending on mode.

**Comment by JonathanDotCel** [comment]
Hi @ymakhno, looks like you didn't read the issue at all.

I asked for a command line arg to skip putting the generated .APKs into another .zip/.apks file.

I didn't ask to break everyone's tool chains by altering the default behaviour.

Options:

 --mode=default produces a bunch of APKS in a APK set (a zip file)
 --mode=universal produces a single APK ... (inside a zip file)
 --mode=system/system_compressed requires the device specs - not particularly helpful if testers have multiple devices to check
 --mode=persistent generates a bunch of APKS in a zip file
 --mode=instant isn't really an option.


All of them potentially waste time by taking the resultant APKs (which are already unzipped) ... and putting them in a .zip file (.apks) ... so we have to unzip them again.

What's the rationale?

**Comment by ymakhno** [comment]
What I wrote you above as universal apk is only one mode which is supported by bundletool. We would prefer to keep output format consistent and always produce apks files from `build-apks`. Because name of command itself says it produces apks, all other bundletool commands `extract-apks` and `install-apks` expect apks, regardless of mode.

**Comment by JonathanDotCel** [comment]
Lol if you're basing it on the command name alone then it's ambiguous anyway

produces "APK"s 
or produces "APKS"

That's not an answer by any means.
Why not a "build-apk" which just skips the final zip step?

Again, what's the rationale for not allowing an unzipped option?

**Comment by plecesne** [comment]
> looks like you didn't read the issue at all.

This comment was probably unnecessary. I too understood your request as wanting a way to build a universal APK without being wrapped inside a zip file per your comment on what the ideal solution would be for you.

The rationale for putting APKs inside a zip file (.apks) is that it can be used as an input to other commands of bundletool, such as `extract-apks` or `installs-apks`, or passed to another team to test if needed. 

The fact that it's a zip file is just an implementation detail by the way, we could have used another format, we don't expect developers to look inside the .apks file, since deciding manually which APKs to install on a device can be error-prone (e.g. most developers wouldn't know the difference between `base-master.apk` and `base-master_2.apk` and are likely to pick one randomly). It's much safer to use bundletool to extract the correct APKs for a device.

Generating APKs inside a directory instead poses some issues. In particular, running a build-apks command twice consecutively would make it impossible to know which APKs were from the first run vs the second run, it would be quite error-prone. One solution would be to clear out the directory before running the command, but this too is dangerous because we don't know what is in the directory. Alternatively, we could throw an exception if the directory is not empty, causing extra burden on developers as they'd need to create an empty directory every time.

For all these reasons, it felt simpler and less error-prone to always generate this .apks file and be consistent across all modes. I hope this clarifies it.

For sending APKs to testers, I would recommend one of the following solutions:

* Sending them an .apks file instead of the AAB. Testers ideally shouldn't have to sign the APKs themselves (as the certificate they use may not be whitelisted with the APIs being used by the app). We understand that in some circumstances, this file can be quite large though if a device spec wasn't specified. An alternative would be to send multiple .apks to the testers, one generated for the device-spec of each of the devices they test.
* Using Play's Internal App Sharing: this feature is 1 year old, and allows you to upload an AAB to Play without the need to sign it and without the need to increase the versionCode. It's completely independent from the tracks in the Play Console. After the upload, you immediately get a link which can be opened on any device to install the app. This is a fast way to share a bundle to another team that only needs to run the app and test exactly what Play would send to that device. See [documentation](https://support.google.com/googleplay/android-developer/answer/9303479).
* Closer to the release, I'd suggest using internal testing track or closed testing track. This way, QA testers once whitelisted will receive byte-for-byte what your users will get once you promote the AAB to the production track. See [documentation](https://support.google.com/googleplay/android-developer/answer/3131213).
* In case you don't care about accuracy of the packaging, you can always send a universal APK. I understand that extracting the universal APK from the .apks file is one extract step, but as @ymakhno said, we had to go for consistency to avoid introducing confusion in the existing command. Adding an extra flag to output to a directory has all the downsides discussed above.

**Comment by JonathanDotCel** [comment]
Thanks for the detailed response, @plecesne.

I see a little better where you're coming from now (.apks = wasteful but cleaner). 

Personally though, I'd take the alternate option (as an option) since you *already* have to specify a unique .apks filename.
    What if it's already there? Exception.
    What if one of your loose .APK files already exits? Same error.
(Likewise, same ballpark for consecutive runs and for installing to the device and not knowing which is which, etc)

I don't agree that a completely optional switch (that you had to go out of your way to find manually to change default behaviour) is confusing. Not more so than "unzipping the .aab just to .zip up all the different versions of your app, zipping those up again, then immediately unzipping it to install...". If anything that's the bit that makes you think you're doing everything wrong. But like you say, not the intended use.

Each of the testing routes has its own set of issues and sending an .AAB for use with an extract/install script has proven to be the most reliable. 
With that said that, that's solid info and thanks for taking the time to type it all out.

**Comment by plecesne** [comment]
Thank you for the feedback. We're going to take it internally with further discussions to see if this is a desirable option for the future.

**Comment by ymakhno** [comment]
Option to produce unzipped APKs is already supported by `--output-format=DIRECTORY` flag in `build-apks` command since 1.3.0.

**Comment by zh325700** [comment]
the difference between two apk is the options in manifest:
master.apk is :android:extractNativeLibs="true"
master_2.apk is :android:extractNativeLibs="false"
my guess is that google will choose one of them while installing to a certain device
