### ISSUE TITLE
Targeting assets to screen density

### ISSUE THREAD

**Issue by plamploika** [google/bundletool#160]
Our application has different assets for different screen pixel density, so we would like to provide certain assets for specific device configurations. I know that this can be done with resources by [providing alternative resources](https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources), but our engine requires working with assets. How can we split assets according to screen density (hdpi, xhdpi, xxhdpi) and take advantages of the Android App Bundle format?

**Comment by plecesne** [comment]
This is not possible today.

**Comment by plamploika** [comment]
@plecesne,
Any plans to add this?
If not, can we clone the repository and change the bundletool in such a way as to create an aab-file with grouped assets by screen density, which we will publish on Google Play? Will this aab-file be valid for the Google Play?

**Comment by plecesne** [comment]
Hey,

Thank you for the interest in this feature (and sorry for my previous very succint reply).
We found that app developers usually rely on different texture compression formats rather than actual densities for assets. That's why Play has recently launched "dynamic asset delivery" with support for texture compression format targeting (https://developer.android.com/guide/app-bundle/asset-delivery).

We don't have immediate plans to support screen densities targeting for assets.

**Comment by mworleybr** [comment]
Just wanted to express our interest in this feature as well, since our application splits assets based on density instead of texture compression.  Are there still no plans to support this?
