### ISSUE TITLE
Installing native app using device specs for armeabi-v7a on device with amd64-v8a cause crash

### ISSUE THREAD

**Issue by Statheres** [google/bundletool#183]
**Describe the bug**
I have native app with armeabi-v7a and amd64-v8a ABI support. I've created custom device specs with targeting only for amd64-v8a and only for armeabi-v7a, built apks and tried to install them to Samsung S8 with both ABI supported. In case of amd64-v8a specs - all works as expected. In case of armeabi-v7a device specs - I've got a crash, related to System.LoadLibrary (can't find native part of the app). 

**Bundletool version(s) affected**
Version: 1.2.0

**To Reproduce**
Build apks with custom specs from attachment (you will find aab and json) and install on device with arm64-v8a ABI support (in my case it was Samsung S8)
[Demo-debug.zip](https://github.com/google/bundletool/files/5339815/Demo-debug.zip)

**Expected behavior**
The application should not crash. I'm not sure about correctness of my issue (maybe it's related more to Android itself) but at least we can get warning or something from bundle tool.

**Comment by ymakhno** [comment]
The `device-spec` flag in `build-apks` command allows to build set of APKs for a concrete device (not for some probably compatible device). Looks like you are using the device spec which is different from your Samsung S8 during `build-apks` and next trying to install the output on Samsung S8 which is not supported.

I agree that we should provide a better error message like: 'Provided APKs file was not generated for the connected device' during `install-apks` command.

If you want to test your app with 32bit libraries on Samsung S8, you still can unpack result apks and install all splits manually via `adb install-multiple` command.

**Comment by Statheres** [comment]
Yep, I understand you. But, arm64-v8a is backward compatible with armeabi-v7a and when I'm building split APKs from android studio, instead of appbundle, both works as intended (including my Samsung S8). Actually that was the reason of my issue

**Comment by ymakhno** [comment]
Just to explain why this is happening. 

`install-apks` command is designed to install version the app on the connected device in a way the app will be installed if you upload the bundle to Google Play. Your app supports `amd64-v8a` as well as your device, so `install-apks` tries to installs APK that contains native libraries for exactly `amd64-v8a` ABI on your device. 

`build-apks` command supports `device-spec` flag to speed-up the development process and generate only APKs that will be installed on the same device next and skip creation of redundant APKs. It doesn't create a different version of the app just skips some APKs that should not be installed. 

So when you are providing a device spec with `armeabi-v7a` ABI to `build-apks` it doesn't create a version of the app that supports only `armeabi-v7a` it just skips creation of APK with `amd64-v8a` ABI but still reports that your app supports both and when you invoke `install-apks` it still tries to install APK with `amd64-v8a` on the device and that's why crash is happening.

If you try to use a device which supports 32bit libraries only and pass its device spec to both `build-apks` and `install-apks` it will work. If you remove 64bit libraries from your app and pass your Samsung S8 spec to both commands they will work as well. 

But If you want to install 32bit libraries from the app which supports 64bit libraries on 64bit device these two commands won't work for you, because this configuration will never appear in production if you upload the bundle. But you definitely can install them manually. 

Hope this explains the motivation.

**Comment by ymakhno** [comment]
Added validation in bundletool 1.4.0 to not extract/install application if required splits are missing in apks file.
