### ISSUE TITLE
Bundletool generates duplicate apk in splits folder

### ISSUE THREAD

**Issue by VladislavAntonyuk** [google/bundletool#192]
**Describe the bug**
Bundletool generates duplicate apk in splits folder

**Bundletool version(s) affected**
Version: 1.3.0

**To Reproduce**
1. unzip [1.zip](https://github.com/google/bundletool/files/5537752/1.zip)
2. run `java -jar bundletool.jar build-apks --bundle "1.aab" --output "1.apks"  --ks="1.jks" --ks-pass=pass:qwerty --ks-key-alias=Alias --key-pass=pass:qwerty --overwrite`

**Expected behavior**
There should be no duplicates

**Known workaround**
unzip apks and remove duplicates

**Environment:**
OS: Windows 10

**Additional context**

**Comment by ymakhno** [comment]
Could you please explain what does mean duplicates? I was able to run bundletool on your bundle and see splits are generated as expected.

**Comment by VladislavAntonyuk** [comment]
Rename 1.apks to 1.apks.zip and open splits folder. You will find 3 files with suffix _2. As a result apks is not able to be installed on the device (I use SAI)

**Comment by VladislavAntonyuk** [comment]
![image](https://user-images.githubusercontent.com/33021114/99107364-66ad2700-25ee-11eb-91ee-35ee830f3f5f.png)

**Comment by plecesne** [comment]
This is WAI. The different APKs are meant for different types of devices.

When running the `build-apks` command without the `--device-spec` flag, bundletool will generate APKs for all types of devices, so you may see multiple APKs with a similar name when opening the `.apks` file.

You can use the `extract-apks` command to extract only the APKs for one device (run `bundletool help extract-apks` for details on how to use the command), or you can use `install-apks` to install the correct APKs directly on a connected device.
Trying to manually pick the APKs by unzipping the `.apks` file will lead to possibly picking the wrong ones and not testing what users would actually receive from the Play Store, so I would discourage it.

Note that you can also include the `--device-spec` flag to the `build-apks` command which would generate the APKs only for the given device spec.

You can find more details on these commands here: https://developer.android.com/studio/command-line/bundletool

**Comment by VladislavAntonyuk** [comment]
what is the difference between  base-arm64_v8a.apk and  base-arm64_v8a_2.apk? I see it as the same base apk for the same platform. but duplicate with the different name and unexpectedly size. as a result it fails to be installed using SAI.

**Comment by ymakhno** [comment]
The difference is: in base-arm64_v8a_2.apk native libraries are stored in uncompressed format to apply "Avoid extracting native libraries" optimization. You can read more about it here: https://developer.android.com/topic/performance/reduce-apk-size#extract-false.

This optimization was introduced in Android SDK 23 and it doesn't make sense to install this APK on devices with SDK 21 and 22 because on such devices native libraries will be extracted anyway but APK size is bigger. So in your example base-arm64_v8a.apk is installed on devices with SDK 21 and 22, and base-arm64_v8a_2.apk is installed on devices with SDK 23 and above.

As Pierre mentioned above we recommend to use `install-apks` bundletool command to install correct splits on a specific device. You can obviously use custom tools like SAI but in this case it is pretty easy to select a wrong splits and test the application with configuration that will never appear to end users.

**Comment by VladislavAntonyuk** [comment]
My min version of Android is SDK 23 (Android 6), so I don’t need that files. Why are they generated?

**Comment by plecesne** [comment]
If you are using native activities, the APKs with uncompressed native libs are only created for devices on SDK 24+.

If your app is installable on external storage (i.e. `install-location=[auto|preferExternal]` in the manifest), the APKs with uncompressed libs are only created for devices on SDK 28+.

**Comment by VladislavAntonyuk** [comment]
changing install-location to internal fixed the issue.

**Comment by congcongc** [comment]
how to convert apks to a single apk? i don't want to use `install-apks ` to install apk directly in my phone.

**Comment by MuntashirAkon** [comment]
Does there exist any mapping or info (e.g. `toc.pb` or `AndroidManifest.xml` of the apk) which can be used to determine which apk splits belong to which SDK?

**Comment by ymakhno** [comment]
To determine which APKs to install on a device you can use `extract-apks` command. Provide it a spec of your device in json format and it will extract only APKs which should be installed.
