### ISSUE TITLE
MANIFEST.MF missed while generating the apk from the aab using bundletool

### ISSUE THREAD

**Issue by ashoktallapelli** [google/bundletool#282]
We upgraded to the latest Gradle 7.2. Before upgrade, it used to work

While generating the apk file from the aab using the bundltool, MANIFEST.MF file is not bundled in the apk. And the MANIFEST.MF file is present in the aab.

If I generate an apk from the Android Studio, then the MANIFEST.MF file is present.

java -jar bundletool-all-1.10.0.jar build-apks --bundle=${OUTPUT_AAB} \
--output=${OUTPUT_APKS} \
--overwrite \
--mode=universal \
--ks=app/${storeFile} \
--ks-pass=pass:${storePassword} \
--ks-key-alias=${keyAlias} \
--key-pass=pass:${keyPassword}

**Comment by chiliwax** [comment]
same problem there :/

**Comment by ymakhno** [comment]
MANIFEST.MF is part of JAR signature. Only legacy APK v1 signature has JAR-compatible format. v1 scheme is deprecated and replaced with a new APK signature scheme v2 starting Android 7 which is not JAR compatible and does not contain MANIFEST.MF. 

If your app has minSdk 24 or above v1 signature is not generated and that's why MANIFEST.MF is not included in generated APKs.
