### ISSUE TITLE
Why the getPackageArchiveInfo function of PackageManager can not get PackageInfo from the Split Apk made by Bundletool.

### ISSUE THREAD

**Issue by wopeiseqi** [google/bundletool#43]
**Describe the bug**
Why the getPackageArchiveInfo function of PackageManager can not getPackageInfo from the Split Apk made by Bundletool.
I want to read split apk made by bundletool packageinfo When I used the func getPackageArchiveInfo  of PackageManager ,but the return result is null.

**Bundletool version(s) affected**
Version: [e.g. 0.6.0]

**Stacktrace**
Copy all of the output of the command, including the stacktrace if visible.

**To Reproduce**
Steps to reproduce the behavior.
Include the full command being run as well as, if possible, artifacts the bug can be reproduced with.

**Expected behavior**
if we can read the packageInfo.

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
Android N

**Additional context**

**Comment by plecesne** [comment]
This isn't a bug of bundletool, this is a general Android question related to split APKs and the PackageManager API. Try stackoverflow for this kind of questions.

Note: when you ask the question there, you may also want to provide additional information, for example, what arguments do you pass to the method, where do you call it from, what log can you find in "adb logcat" at the moment of the call, etc. and if possible at all, can you provide a simple example so that others can reproduce locally.

**Comment by wopeiseqi** [comment]
Thanks
