### ISSUE TITLE
when build the apks, there are two base-master.apk (base-maseter.apk, base-master2.apk)

### ISSUE THREAD

**Issue by wopeiseqi** [google/bundletool#53]
**Describe the bug**
when build the apks, there are two base-master.apk (base-maseter.apk, base-master2.apk)
why there are two base-master.apk ?
**Bundletool version(s) affected**
Version: [e.g. 0.8.0]

**Stacktrace**

**To Reproduce**
Steps to reproduce the behavior.
Include the full command being run as well as, if possible, artifacts the bug can be reproduced with.

**Expected behavior**

**Known workaround**
If you have found a workaround, please specify what it is.

**Environment:**
OS:window 10

**Additional context**

**Comment by wopeiseqi** [comment]
maybe abi compress different

**Comment by plecesne** [comment]
In [bundletool 0.6.0](https://github.com/google/bundletool/releases/tag/0.6.0), we enabled the optimization called *uncompressed native libraries* for devices on Android M and above. 

This allows native libraries to remain uncompressed in the APK so that the Android platform doesn't have to uncompress them on the device to be able to read them. This leads to a size reduction of the app on the user device as well as a reduction in download size as well (due to compression algorithms performing better on uncompressed data). The optimization is guarded by the attribute `extractNativeLibs=false` in the AndroidManifest.xml which is why not only the APKs with native libraries will differ (on the compression), but also the master APK (for the manifest).

Because this optimization is available since Android M only, we generate two variants of the APKs, the compressed native libraries for devices on L and before, and the uncompressed native libraries for devices on M and later.

Calling `bundletool install-apks` selects the right APKs for the right device automatically based on the SDK version.

**Comment by overetch** [comment]
plecesne, Thanks for your replay! Now it's much clearer to understand!
