### ISSUE TITLE
Add bundletool-all.jar to Maven

### ISSUE THREAD

**Issue by changusmc** [google/bundletool#58]
**Is your feature request related to a problem? Please describe.**
We have a local mirror of Maven. Our CI doesn't have access to GitHub, and updating versions of the JAR requires us to download the `all` jar from GitHub and checking it into our repo. It would be more convenient for version bumps if we could download the dependency from Maven instead.

**Describe the solution you'd like**
Provide `bundletool-all-0.9.0.jar` in maven.google.com

**Describe alternatives you've considered**
Download the Jar and check into our repo

**Comment by plecesne** [comment]
I believe Maven's primary goal is to download library dependencies, but if I understand correctly, you would like to use it just to download a binary tool here, is that correct?

The problem I see with this is that bundletool-all.jar already includes all the compiled dependencies, which makes it unusable if you compile it in a project that depends on any other library (since the dependency versions might conflict). So not only pushing bundletool-all.jar to Maven would go against the principles behind Maven repository system, but this would also lead to a brittle system.

Could you use GitHub API and make an http request to fetch the bundletool-all.jar from the latest release?

**Comment by changusmc** [comment]
You are correct in that is my intended usage. I'm interested in getting the
binary tool and I want to be able to up-version it easily.

If the file was available in Maven, I could tell our CI to download the
file from our internal mirror (since I would like to *not* check in the
binary into our source control). Our CI doesn't have GitHub or internet
access.

I must have misunderstood the usage of Maven repos, but I see some "all'
jars here: https://mvnrepository.com/search?q=all


Thanks,D
avid

**Comment by plecesne** [comment]
The "all" artifacts you see in this mvnrepository query mean "all modules" for libraries that have decided to split their libraries in multiple smaller modules: they still don't include dependencies and they're definitely not executable binaries.

For the reasons I've mentioned in my previous comment, we don't have the intention to publish the binary in Maven today.

I would suggest you turn to alternative solutions. For example, the same way you seem to have a tool that makes an offline copy of the Maven libraries you depend on, you could have a similar tool that will download the latest version of bundletool from GitHub to have it available offline for your CI.
