### ISSUE TITLE
How to keep some resources in the base APK with the build-bundle command?

### ISSUE THREAD

**Issue by wopeiseqi** [google/bundletool#59]
How to keep some resources in the base APK with the build-bundle command?  how to write the command for keeping resource in the base apk.

**Comment by kvafy** [comment]
This issue seems to be closely related to #52. Can you please follow-up and answer the original [question](https://github.com/google/bundletool/issues/52#issuecomment-472837070) - why is such functionality needed in your use case?


That being said, there is a way of forcing specific resource IDs to be kept in the master split by passing in a customized BundleConfig file:
```
$ bundletool build-bundle --config=<path/to/BundleConfig.pb.json> ...
```
Within the BundleConfig.pb.json you need to specify the resource IDs:
```
{
  "master_resources": {
    "resource_ids": [
      2130771968
    ]
  }
}
```
