### ISSUE TITLE
Drawable items are missing in mdpi apk

### ISSUE THREAD

**Issue by kzotin** [google/bundletool#64]
**Describe the bug**
Drawable resources, which IDs are defined in library module and actual images are in app module, are not part of mdpi APKs, made from AppBundle.

Code example is located here:
https://github.com/kzotin/appbundle-mdpi-bug

**Bundletool version(s) affected**
Version: 0.9.0

**To Reproduce**
1) Define drawable resource in the library module
2) Add actual image to app module
3) Build bundle: `gradlew bundleRelease`
4) Use bundletool to create result APKs
5) Check standalone APKs: hdpi, xhdpi, xxhdpi, xxxhdpi have icon, but mdpi APK does not.

**Expected behavior**
Icon exists in mdpi APK

**Environment:**
OS: Any

**Comment by kvafy** [comment]
Thank you for discovering this bug!

The root cause is within the Android Gradle plug-in. The bundletool merely honors the misleading resource configuration that is stored inside the bundle.

I have filed a bug with the plug-in team (visible as [Issue 130346674](https://issuetracker.google.com/130346674)).

**Comment by kzotin** [comment]
Hi @kvafy,
I've noticed that issue is marked as **Intended Behavior**. 
Could you please add more details - why it's decided this way and what is the best workaround?

**Comment by plecesne** [comment]
[Comment #6](https://issuetracker.google.com/issues/130346674#comment6) on the bug explains what was wrong with the project.

In short, these resources were declared without values in the default drawable directory, and the default drawable directory is equivalent to the `mdpi` screen density, thus this project indicated that for `ldpi` and `mdpi` these should be the resources used... but due to the [lack of values](https://github.com/kzotin/appbundle-mdpi-bug/blob/master/mylibrary/src/main/res/values/ids.xml) associated to these resources, it defaulted to an empty string and a null reference.

The solution is just not to define resources without values, even in the default drawable directory.
