### ISSUE TITLE
apk size is larger than aab

### ISSUE THREAD

**Issue by JingYeoh** [google/bundletool#75]
**Describe the bug**
apk(build by bundletool) size(92M) is larger than aab size(91M), is there any args to compress apk size(use zip or 7z)? 

**Bundletool version(s) affected**
0.9.0

**To Reproduce**
use bundletool build apks and apk

**Expected behavior**
apk size is smaller than aab size

**gradle config**
```
bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = true
        }
        abi {
            enableSplit = true
        }
    }
```

**device-spec json**
```json
{
  "supportedAbis": [
    "armeabi-v7a"
  ],
  "supportedLocales": [
    "zh-CN",
    "en-US",
    "ja-JP",
    "zh-HK",
    "zh-TW"
  ],
  "screenDensity": 480,
  "sdkVersion": 20
}
```

> please tell me if you need other information

**Comment by plecesne** [comment]
How are you measuring the size of your APK? If you're just looking at the size of the file on disk, this is irrelevant. There was just a [talk at Google I/O](https://youtu.be/rEuwVWpYBOY?t=893) on how app size should be measured and I invite you to take a look.

When you start looking at the download size, you should see that your APK size is actually much smaller. The reason is that keeping some files uncompressed in the APK is actually reducing the visible size of your app to users. Although your size on disk looks bigger, the APK is compressed when being served over the wire and Google is able to perform better compression on uncompressed files. Also, on the device, the Android platform is able to memory-map the native libraries when they're uncompressed (since SDK 22), which avoids the need of making a copy of them on the device.

**Comment by JingYeoh** [comment]
thanks for your answer, below table is our apk size data

|build source|APK size|Download size|
|-------|---------|--------------|
|assemble|78.2MB|76.7MB|
|bundletool|92MB|80.1MB|

**we use 7zip to compress apk size for assemble, so it's download size is smaller than aab apk.**

![WX20190514-214813](https://user-images.githubusercontent.com/20204119/57703277-554e2c00-7692-11e9-9621-f471bad888ea.png)
![WX20190514-214833](https://user-images.githubusercontent.com/20204119/57703871-72cfc580-7693-11e9-826c-8bd5a2146c60.png)

the new apk and old apk almost have the same files, but the apk diff size is 13.8MB, that could be very nice if bundletool do something make apk more smaller  (;

**Comment by plecesne** [comment]
Are you able to tell from the size breakdown which files are bigger when generated by bundletool?

**Comment by JingYeoh** [comment]
![WX20190515-104927](https://user-images.githubusercontent.com/20204119/57745313-418cdf00-76ff-11e9-8af7-afddd2960de5.png)

resources.arsc is bigger because we obfuscated resources for aab and apk, but `res` dir name must be keeped for `bundletool` ([BundleFilesValidator](https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/validation/BundleFilesValidator.java#L112))

two apk diff size is 11.4MB
