### ISSUE TITLE
Google play download size is larger

### ISSUE THREAD

**Issue by JingYeoh** [google/bundletool#87]
we used the bundle to build an `.aab` file，and use **bundletool get-size total** command to get download size(65M)，and we upload `*.aab` to google play, but the size in google play is more larger(78M).
![image](https://user-images.githubusercontent.com/20204119/61029549-dead8080-a3ed-11e9-876e-d7897a1c8b46.png)
![image](https://user-images.githubusercontent.com/20204119/61029576-eff68d00-a3ed-11e9-9d44-2a2b3e428b44.png)

disk size is 78.3M

i think the size in GP is not the download size, maybe it's disk size?

**Comment by plecesne** [comment]
Bundletool measures the download size (i.e. gzipped size of the APKs), not the disk size.

We would need to see the AAB file and check your app in the Play Store to understand why you are seeing a bigger size in the Play Store.
Would you be able to reach out to the [Play developer support team](https://support.google.com/googleplay/android-developer/answer/7218994), give them your AAB, the details of your app and what you ran, and link to this bug so that I can run the investigation with all the needed data without you having to share everything in here?

**Comment by JingYeoh** [comment]
I got below reply, i think this should be helpful for others 

**Internal sharing does not support compression yet, so when installing through internal sharing we see the full app install size.
This is generally larger than the compressed size shown in Play Console, bundletool, actual prod install from the store etc.
Given that this is just used by testers it doesn't make sense to compress for data bandwidth reasons. It might make sense for purposes of simulating the true prod experience better (i.e. showing the realistic download size and alleviating concerns like that raised here). But we'd need to prioritize this, it is not a trivial amount of work.**

**Comment by choisin** [comment]
> 

thank you. It was helpful. From August 2021, uploading of aab apps is compulsory.
So there was a lot of confusion during the process of testing the app with internal tests.
In the closed test, we will test whether we can receive the app in a normally compressed capacity.
