### ISSUE TITLE
"The syntax of the command is incorrect." for --key-pass=pass: when an alias key pass ends with a '>'

### ISSUE THREAD

**Issue by aaronhoogstraten** [google/bundletool#95]
**Describe the bug**
My signing alias key password ends with a right angle bracket '>' and if I try to provide it in the "--key-pass=pass:" argument it results in a "The syntax of the command is incorrect." error.

**Bundletool version(s) affected**
Version: tested with 0.6.0 and 0.10.2

**Stacktrace**
"The syntax of the command is incorrect."

**To Reproduce**
Generate a keystore with an alias key password ending with a right angle bracket '>' and attempt to use the build-apks command while providing signing credentials with "-key-pass=pass:*****>" 

**Expected behavior**
The signing works with a commandline provided password.

**Known workaround**
As a workaround I instead pasted my alias key pass into a file and used the "-key-pass=file:" argument which worked.

**Environment:**
OS: Windows 10 Pro

**Comment by kvafy** [comment]
This is likely an issue with how the Windows command line interprets ">". I see two possible explanations:

- Your password ends up containing some special character sequence due to accidental escaping or due to other control characters (backslashes etc).
- You haven't put the whole --key-pass argument into quotes (ie. `"--key-pass=pass:*****>"` vs `--key-pass=pass:*****>`) in which case ">" is likely interpreted by the shell as redirection of stdout, and not as a part of the password.

**Comment by aaronhoogstraten** [comment]
> You haven't put the whole --key-pass argument into quotes (ie. "--key-pass=pass:*****>" vs --key-pass=pass:*****>) in which case ">" is likely interpreted by the shell as redirection of stdout, and not as a part of the password.

This was indeed the case! Putting the whole argument in quotes was successful. Cheers!
