### ISSUE TITLE
Support generating debuggable APKs

### ISSUE THREAD

**Issue by benjaminRomano** [google/bundletool#96]
**Is your feature request related to a problem? Please describe.**
In our release pipeline, we perform dex optimizations after generating an app bundle. To perform one of the optimizations, we extract a universal apk, make it debuggable and do some processing.

We are now looking into dynamic delivery and with a dynamic feature enabled, we are no longer able to make the APK debuggable as the tool we use, `apktool`, does not support disassembling/assembling multi-package ResourceTables.

Another motivation for this change is that we currently disable `debuggable` on our internal builds due to significant performance penalty. To create an internal build that is debuggable we need to kick off two builds. This would help streamline the process. 

**Describe the solution you'd like**
I would like to add a `debuggable` option to `build-apks` to allow overriding the `debuggable` property in `AndroidManifest.xml`.  

**Describe alternatives you've considered**
Another solution I considered was extracting out the `AndroidManifest.xml` from the generated apk adding the `debuggable` flag and adding it back to the APK, but I haven't had success with that approach as the manifest is stored in the apk as `axml`.

I also considered making the fix to `apktool`, but during re-assembling `aapt2` only supports specifying one resource package. 

Here is what I'd expect this to look like https://github.com/google/bundletool/pull/97

**Comment by ymakhno** [comment]
I see this issue is abandoned and probably is already resolved in your build pipeline. But even if not I don't think this is something we want to add into bundletool as this request is very specific for a concrete build pipeline.

If this is still the issue I would recommend to use bundletool as a library and pass custom [ApkModifier](https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/model/ApkModifier.java#L25) implementation to [BuildApksCommand](https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/commands/BuildApksCommand.java#L423).
